# Generated by Django 2.2 on 2019-04-18 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_company', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('web', models.CharField(max_length=50)),
                ('id_sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.Sector')),
            ],
        ),
    ]
