# Generated by Django 2.2 on 2019-04-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='id_sector',
            new_name='sector',
        ),
    ]
