# Generated by Django 2.2 on 2019-04-18 16:53

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20190418_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('espesor_minimo', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=10)),
                ('espesor_maximo', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=10)),
                ('espesor_nominal', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=10)),
                ('espesor_retiro', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=10)),
                ('espesor_permitida', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('coste', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=10)),
                ('peso', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=10)),
                ('volumen', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.Area')),
            ],
        ),
        migrations.RenameField(
            model_name='company',
            old_name='nom_company',
            new_name='nombre',
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='SubComponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Componente')),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Division')),
            ],
        ),
        migrations.CreateModel(
            name='Modo_Falla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('subComponente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.SubComponente')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.Tipo'),
        ),
        migrations.AddField(
            model_name='division',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Company'),
        ),
        migrations.AddField(
            model_name='componente',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Equipo'),
        ),
        migrations.AddField(
            model_name='area',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Planta'),
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Tecnica')),
            ],
        ),
    ]
